workflows:
  ios-release-build:
    name: iOS Release Build
    instance_type: mac_mini_m2
    max_build_duration: 30
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter dependencies
        script: |
          flutter packages pub get
      - name: Install CocoaPods dependencies
        script: |
          find . -maxdepth 2 -name "Podfile" -execdir pod install \;
      - name: Build iOS IPA
        script: |
          flutter build ipa --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive
      - /Users/builder/clone/build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - user@example.com
        notify:
          success: true
          failure: true

  android-release-build:
    name: Android Release Build
    instance_type: linux_x2
    max_build_duration: 30
    environment:
      flutter: stable
      java: 17
    scripts:
      - name: Get Flutter dependencies
        script: |
          flutter packages pub get
      - name: Build Android APK
        script: |
          flutter build apk --release --no-tree-shake-icons
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
